### PR TITLE
Add defaults to engine specific params in model docs

### LINKED ISSUE #211: Create a reference / cheat sheet mapping engine-specific parameters to parsnip ones?
As I'm going through converting algorithm-specific logic to generalized parsnip model specifications, one thing I am thinking that could be useful would be to create one or more reference tables or "cheat sheets" in the parsnip docs describing how to map from implemention-specific parameters (e.g. "eta" in xgboost) to parsnip model parameters (e.g. "learn_rate" in parsnip::boost_tree()).

The simplest form would probably just be a collection of tables (one per model), with columns for each supported engine + a final column corresponding to the parsnip parameter names.

Since this could take a bit of time to add, perhaps if you think this sort of thing would be useful, you could decide on an appropriate location/format, and add placeholders.

Then, myself and other users could help fill it in as we use the models.

### PR DESCRIPTION
**Pull request by juliasilge**
This PR closes #211.

What I have so far here is my initial idea of how to add the default values for each engine specific parameter into the tables in the docs. These values are only needed for `devtools::document()` so I am thinking let's make little internal functions via `paste0()` rather than `get_model_env()` and add all these values via some `set_...` function and keep them around.

What are your thoughts?

Current results for the one model implemented right now:

``` r
library(parsnip)
convert_args("decision_tree")
#> Joining, by = c("model", "engine", "parsnip", "original")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>parsnip</strong></th>
<th style="text-align: left;"><strong>rpart</strong></th>
<th style="text-align: left;"><strong>C5.0</strong></th>
<th style="text-align: left;"><strong>spark</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">tree_depth</td>
<td style="text-align: left;">maxdepth (30)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">max_depth (5)</td>
</tr>
<tr class="even">
<td style="text-align: left;">min_n</td>
<td style="text-align: left;">minsplit (20)</td>
<td style="text-align: left;">minCases (2)</td>
<td style="text-align: left;">min_instances_per_node (1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cost_complexity</td>
<td style="text-align: left;">cp (0.01)</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### CODE REVIEW

**Comment by apreshill** [comment]
@juliasilge I believe this also would close https://github.com/tidymodels/parsnip/issues/235? :tada:

**Comment by juliasilge** [comment]
For now I'm only adding these to the tables in the docs, with functions that are only run during `devtools::document()`. So no user-facing functions quite yet.

Users could look at the docs and get the values but we haven't moved quite all the way to a dynamic lookup.

**Comment by juliasilge** [comment]
We're going to have to make a call on what to do with the `rand_forest()` table, for `mtry` and `min_n`.

For ranger's `mtry`:
```
Number of variables to possibly split at in each node. Default is the (rounded down) square root
of the number variables. Alternatively, a single argument function returning an integer, given the 
number of independent variables.
```

For ranger's `min.node.size`:
```
Minimal node size. Default 1 for classification, 5 for regression, 3 for survival, and 10 for 
probability.
```
Neither of these are available via `formals()`.

For randomForest, the function argument themselves are defined as:

```r
mtry=if (!is.null(y) && !is.factor(y))
             max(floor(ncol(x)/3), 1) else floor(sqrt(ncol(x)))

nodesize = if (!is.null(y) && !is.factor(y)) 5 else 1
```
I think I'm going to put some of these in manually.

**Comment by topepo** [comment]
Yes. I would add them as expressions to your data structure. Maybe something like "1C|5R|3S" with a legend on the bottom?

**Comment by juliasilge** [comment]
The issues around `rand_forest()` and SVM make me think #235 is going to be **quite** difficult.

**Comment by juliasilge** [comment]
The SVM options are less than ideal. They are hard-coded mostly, and I dug around in the liquidSVM code and came up with... this:

```r
> convert_args("svm_rbf")
```

|**parsnip** |**kernlab**   |**liquidSVM**    |
|:-----------|:-------------|:----------------|
|cost        |C (1)         |lambdas (varies) |
|rbf_sigma   |sigma (1)     |gammas (varies)  |
|margin      |epsilon (0.1) |NA               |

Hmmm

**Comment by juliasilge** [comment]
I updated the `sigma` value for kernlab because although `rbfdot()` has a default of 1, during training the value used depends on the data.

**Pull request merged**
