### PR TITLE
Add dann models

### PR DESCRIPTION
**Pull request by gmcmacran**
This pull request adds the nearest_neighbor_adaptive to parsnip. Engines are the tidydann package.

### CODE REVIEW

**Comment by gmcmacran** [comment]
https://github.com/tidymodels/parsnip/issues/996

**Comment by gmcmacran** [comment]
https://github.com/gmcmacran/tidydann/issues/7

**Comment by simonpcouch** [comment]
Thank you for the PR! Your [comment re: dependencies](https://github.com/gmcmacran/tidydann/issues/7#issuecomment-1749949015) makes sense given your interpretation of Max's issue—implementing this approach is indeed tricky.

Max is OOO for a bit now, so I'll be the first touch point. I believe his intent was to suggest that the tidydann package receives the suggested changes rather than parsnip.

By your interpretation, this would involve renaming the `dann()` and `sub_dann()` model types to `nearest_neighbor_adaptive()`, with `"dann"` and `"sub_dann"` being engines. Those changes would happen in tidydann.

A lower-friction way to implement that might be to make `"dann"` and `"sub_dann"` engines for the existing `nearest_neighbor()` model type from parsnip. [Here is an example](https://github.com/tidymodels/bonsai/blob/main/R/lightgbm_data.R) of adding a new engine to an existing model type, where the engine is `"lightgbm"` and the model type is `boost_tree()`. Once you've done so, parsnip itself needs no changes—loading the tidydann package will automatically hook into parsnip's machinery to recognize the engine.

**Comment by gmcmacran** [comment]
Thanks for feedback. I will move the model functions back into tidydann. Closing PR.

**Pull request closed without merging**
