### PR TITLE
add release bullets

### PR DESCRIPTION
**Pull request by topepo**
Anything else that we should add?

### CODE REVIEW

**Comment by hfrick** [comment]
there is already a `release_bullets()` function in parsnip in `R/aaa.R` so we should consolidate them. Can we add pkg-level docs for parsnip and put release bullets, imports, global variables, etc there?

**Comment by topepo** [comment]
Ok. Is there a canonical place that we put them? In tune, they are in 0_imports.R

**Review by EmilHvitfeldt — APPROVED** [review]

**Comment by hfrick** [comment]
@topepo could you run `document()` on this, please? I am having the same codecogs issue as Emil.

**Review by DavisVaughan — APPROVED** [review]

**Comment by topepo** [comment]
@hfrick ✅ 

Should I merge?

**Pull request merged**
