### PR TITLE
transition `update` internals

### PR DESCRIPTION
**Pull request by simonpcouch**
See #691 and https://github.com/tidymodels/parsnip/issues/691#issuecomment-1104277990. :)

### CODE REVIEW

**Comment by simonpcouch** [comment]
re: follow-up discussion from the group meeting, going to go ahead and work some `update` refactoring into this PR. :)

A la

https://github.com/tidymodels/parsnip/blob/68dfd60cf70beee26035d26cdc581354b7a22e92/R/mlp.R#L103

**Comment by simonpcouch** [comment]
Okay, good to go! This PR now refactors the internals of `update` methods a bit more thoroughly and consolidates their unit tests.

One thing worth mentioning—I'm not sure if this was intended behavior, but `update_engine_parameters` used to retain engine args even when `fresh = TRUE`:

``` r
pak::pkg_install("tidymodels/parsnip")
#> ℹ Loading metadata database
#> ℹ Loading metadata database
  
library(parsnip)  
  
linear_reg(mixture = 0) %>% 
  set_engine("glmnet", nlambda = 10) %>% 
  update(penalty = 1, fresh = TRUE)
#> Linear Regression Model Specification (regression)
#> 
#> Main Arguments:
#>   penalty = 1
#> 
#> Engine-Specific Arguments:
#>   nlambda = 10
#> 
#> Computational engine: glmnet
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It now handles engine args in the same way we've previously handled main ones:

``` r
pak::pkg_install("tidymodels/parsnip@engine-params-691")
#> ℹ Loading metadata database
#> ℹ Loading metadata database
  
library(parsnip)  
  
linear_reg(mixture = 0) %>% 
  set_engine("glmnet", nlambda = 10) %>% 
  update(penalty = 1, fresh = TRUE)
#> Linear Regression Model Specification (regression)
#> 
#> Main Arguments:
#>   penalty = 1
#> 
#> Computational engine: glmnet
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


🐝

**Review by juliasilge — APPROVED** [review]
This is really an improvement that will help a lot! 🙌 Consolidating those tests is a great move.

**Comment by topepo** [comment]
> One thing worth mentioning—I'm not sure if this was intended behavior, but `update_engine_parameters` used to retain engine args even when `fresh = TRUE`

That was not intended. Can you update this PR with that change?

**Comment by simonpcouch** [comment]
@topepo That change is already made here! Added a bullet to NEWS re: that fix—give me a holler if that's not what you meant.

**Comment by simonpcouch** [comment]
Glad to fix merge conflicts if this PR is otherwise good to go!🐨

**Pull request merged**
