### PR TITLE
handle `NULL` objective in `xgb_predict()`

### LINKED ISSUE #873: Try Customizing objective function in XGboost.
``` r
library(tidymodels)
library(tidyverse)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice



data<- iris |> as_tibble() |> 
  filter(Species!="setosa")

mydata |> view()
#> Error in view(mydata): object 'mydata' not found
mydata<- data |> 
  rename(y=Species) |> 
  mutate(y = as.numeric(y)-2) 
labels <- mydata$y
features <- mydata[, -1]


# Convert your data to a DMatrix object
dtrain <- xgb.DMatrix(data = as.matrix(features), label = labels)

new_data <- mydata[1:100, -1]

dtest <- xgb.DMatrix(data = as.matrix(new_data))


# for check exactly same result -------------------------------------------

# user define objective function, given prediction, return gradient and second order gradient
# this is log likelihood loss
logregobj <- function(preds, dtrain) {
  labels <- xgboost::getinfo(dtrain, "label")
  preds <- 1 / (1 + exp(-preds))
  grad <- preds - labels
  hess <- preds * (1 - preds)
  return(list(grad = grad, hess = hess))
}



# should be same results  -------------------------------------------------

params <- list(
  objective = "binary:logistic",
  #eval_metric = "logloss",
  eta = 0.1,
  max_depth = 5
)


param_org <- list(objective = logregobj,
                  base_score= 0.0,
                  eta = 0.1,
                  max_depth = 5 )

# model -------------------------------------------------------------------

num_round <- 10
xgb_model <- xgb.train(params, dtrain, num_round)
xgb_model_custom <- xgb.train(param_org, dtrain, num_round)



logistic_f <- function(x){
  1/(1+exp(-x))
}


custom_obj<- predict(xgb_model_custom, dtest) |> logistic_f()
default_obj<- predict(xgb_model, dtest)

# almost same!!!
(default_obj-custom_obj) |> range()
#> [1] -3.296303e-08  1.806186e-08



# I want to this custom obj function into tidymodel ecosystem ---------------------


set.seed(100)

data<- iris |> as_tibble() |> 
  filter(Species!="setosa") 
mydata<- data |> 
  rename(y=Species) 
#mydata |> view()
splits<- initial_split(mydata,prop = 0.8,strata = y)
train_data <- training(splits)
test_data <- testing(splits)

resamples<- vfold_cv(data = train_data,v = 5,strata = y)


xgboost_model <- boost_tree( mode = "classification",
                               tree_depth     =tune(),
                               trees           =tune(),
                               learn_rate     =tune(),
                               mtry           =tune(),
                               min_n          =tune(),
                               loss_reduction =tune(),
                               sample_size    =tune(),
                               stop_iter      =tune()
) %>% set_engine(engine = "xgboost" ,
                 objective = logregobj,
                 base_score= 0.0,
                 set.seed = 100)

xgboost_model |> translate()
#> Boosted Tree Model Specification (classification)
#> 
#> Main Arguments:
#>   mtry = tune()
#>   trees = tune()
#>   min_n = tune()
#>   tree_depth = tune()
#>   learn_rate = tune()
#>   loss_reduction = tune()
#>   sample_size = tune()
#>   stop_iter = tune()
#> 
#> Engine-Specific Arguments:
#>   objective = logregobj
#>   base_score = 0
#>   set.seed = 100
#> 
#> Computational engine: xgboost 
#> 
#> Model fit template:
#> parsnip::xgb_train(x = missing_arg(), y = missing_arg(), weights = missing_arg(), 
#>     colsample_bynode = tune(), nrounds = tune(), min_child_weight = tune(), 
#>     max_depth = tune(), eta = tune(), gamma = tune(), subsample = tune(), 
#>     early_stop = tune(), objective = logregobj, base_score = 0, 
#>     set.seed = 100, nthread = 1, verbose = 0)




rec_base<- train_data |> 
  recipe(y~.) #%>%
  #step_mutate_at(all_numeric_predictors(), fn = list(orig = ~.)) %>%
 # step_normalize(all_predictors(), -all_outcomes())




xgboost_workflow <- 
  workflow() %>% 
  add_recipe(rec_base) %>% 
  add_model(xgboost_model)



param_info <- 
  xgboost_workflow %>%
  extract_parameter_set_dials() %>%
  finalize(train_data) |> 
  update(
    trees = trees(range = c(5L,1500L)),
    tree_depth= tree_depth(range = c(2L,15L)),
    learn_rate = learn_rate(range = c(-5,-0.5)),
    loss_reduction = loss_reduction(range = c(-5,1.5))
    
  )
#fit_xy.model_spec()

grid_size <- 3
set.seed(100)
xgboost_tune <-
  tune_grid(xgboost_workflow,
            resamples = resamples,
            grid = grid_latin_hypercube(param_info,size = grid_size),
            control =control_grid(verbose = TRUE,
                                  allow_par = FALSE,
                                  parallel_over =NULL,save_pred = FALSE),
            metrics = metric_set(mcc)#rank_percentile_rmse
  )
#> i Fold1: preprocessor 1/1
#> ✓ Fold1: preprocessor 1/1
#> i Fold1: preprocessor 1/1, model 1/3
#> ✓ Fold1: preprocessor 1/1, model 1/3
#> i Fold1: preprocessor 1/1, model 1/3 (predictions)
#> x Fold1: preprocessor 1/1, model 1/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold1: preprocessor 1/1, model 2/3
#> ✓ Fold1: preprocessor 1/1, model 2/3
#> i Fold1: preprocessor 1/1, model 2/3 (predictions)
#> x Fold1: preprocessor 1/1, model 2/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold1: preprocessor 1/1, model 3/3
#> ✓ Fold1: preprocessor 1/1, model 3/3
#> i Fold1: preprocessor 1/1, model 3/3 (predictions)
#> x Fold1: preprocessor 1/1, model 3/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold2: preprocessor 1/1
#> ✓ Fold2: preprocessor 1/1
#> i Fold2: preprocessor 1/1, model 1/3
#> ✓ Fold2: preprocessor 1/1, model 1/3
#> i Fold2: preprocessor 1/1, model 1/3 (predictions)
#> x Fold2: preprocessor 1/1, model 1/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold2: preprocessor 1/1, model 2/3
#> ✓ Fold2: preprocessor 1/1, model 2/3
#> i Fold2: preprocessor 1/1, model 2/3 (predictions)
#> x Fold2: preprocessor 1/1, model 2/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold2: preprocessor 1/1, model 3/3
#> ✓ Fold2: preprocessor 1/1, model 3/3
#> i Fold2: preprocessor 1/1, model 3/3 (predictions)
#> x Fold2: preprocessor 1/1, model 3/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold3: preprocessor 1/1
#> ✓ Fold3: preprocessor 1/1
#> i Fold3: preprocessor 1/1, model 1/3
#> ✓ Fold3: preprocessor 1/1, model 1/3
#> i Fold3: preprocessor 1/1, model 1/3 (predictions)
#> x Fold3: preprocessor 1/1, model 1/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold3: preprocessor 1/1, model 2/3
#> ✓ Fold3: preprocessor 1/1, model 2/3
#> i Fold3: preprocessor 1/1, model 2/3 (predictions)
#> x Fold3: preprocessor 1/1, model 2/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold3: preprocessor 1/1, model 3/3
#> ✓ Fold3: preprocessor 1/1, model 3/3
#> i Fold3: preprocessor 1/1, model 3/3 (predictions)
#> x Fold3: preprocessor 1/1, model 3/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold4: preprocessor 1/1
#> ✓ Fold4: preprocessor 1/1
#> i Fold4: preprocessor 1/1, model 1/3
#> ✓ Fold4: preprocessor 1/1, model 1/3
#> i Fold4: preprocessor 1/1, model 1/3 (predictions)
#> x Fold4: preprocessor 1/1, model 1/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold4: preprocessor 1/1, model 2/3
#> ✓ Fold4: preprocessor 1/1, model 2/3
#> i Fold4: preprocessor 1/1, model 2/3 (predictions)
#> x Fold4: preprocessor 1/1, model 2/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold4: preprocessor 1/1, model 3/3
#> ✓ Fold4: preprocessor 1/1, model 3/3
#> i Fold4: preprocessor 1/1, model 3/3 (predictions)
#> x Fold4: preprocessor 1/1, model 3/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold5: preprocessor 1/1
#> ✓ Fold5: preprocessor 1/1
#> i Fold5: preprocessor 1/1, model 1/3
#> ✓ Fold5: preprocessor 1/1, model 1/3
#> i Fold5: preprocessor 1/1, model 1/3 (predictions)
#> x Fold5: preprocessor 1/1, model 1/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold5: preprocessor 1/1, model 2/3
#> ✓ Fold5: preprocessor 1/1, model 2/3
#> i Fold5: preprocessor 1/1, model 2/3 (predictions)
#> x Fold5: preprocessor 1/1, model 2/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> i Fold5: preprocessor 1/1, model 3/3
#> ✓ Fold5: preprocessor 1/1, model 3/3
#> i Fold5: preprocessor 1/1, model 3/3 (predictions)
#> x Fold5: preprocessor 1/1, model 3/3 (predictions): Error in switch(object$params$objective, `binary:logitraw` = stats::bino...
#> Warning: All models failed. Run `show_notes(.Last.tune.result)` for more
#> information.

show_notes(.Last.tune.result)
#> unique notes:
#> ────────────────────────────────────────────────────────────────────────────────
#> Error in switch(object$params$objective, `binary:logitraw` = stats::binomial()$linkinv(res), : EXPR must be a length 1 vector
```

I checked through Google that there are basic options such as objective="binary:logistic", is there any way to change this to any function I made?

Thank you for always creating and maintaining the tidy ecosystem.

### PR DESCRIPTION
**Pull request by simonpcouch**
_This PR ought not to be merged before the upcoming 1.0.4 release._

Closes #873!

This PR:

* Handles `NULL` objectives in `xgb_predict()`
* Tests an additional type of alternative objective and tests each alternative objective not only for fitting but for predicting

The reason we need to be able to handle `NULL` objectives is because the `xgb.Booster` object will not carry along the `objective` argument in its `params` slot if's not one of the pre-defined options. Using the example fit and custom objective fn from the `xgb.train()` examples:

``` r
library(tidymodels)
library(xgboost)

data(agaricus.train, package = "xgboost")
data(agaricus.test, package = "xgboost")

dtrain <- with(agaricus.train, xgb.DMatrix(data, label = label, nthread = 2))
dtest <- with(agaricus.test, xgb.DMatrix(data, label = label, nthread = 2))
watchlist <- list(train = dtrain, eval = dtest)
```

The `objective` parameter is retained, usually:

``` r
param <- list(max_depth = 2, eta = 1, nthread = 2,
              objective = "binary:logistic", eval_metric = "auc")
bst <- xgb.train(param, dtrain, nrounds = 2, watchlist)
#> [1]  train-auc:0.958228  eval-auc:0.960373 
#> [2]  train-auc:0.981413  eval-auc:0.979930

bst$params$objective
#> [1] "binary:logistic"

# But is not brought along when a custom objective function is used:
logregobj <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  preds <- 1/(1 + exp(-preds))
  grad <- preds - labels
  hess <- preds * (1 - preds)
  return(list(grad = grad, hess = hess))
}

param$objective <- logregobj

bst <- xgb.train(param, dtrain, nrounds = 2, watchlist)
#> [1]  train-auc:0.958228  eval-auc:0.960373 
#> [2]  train-auc:0.981413  eval-auc:0.979930

bst$params$objective
#> NULL
```

The "more minimal" reprex from the original issue, with this PR installed:

``` r
res <-
  fit_resamples(
    boost_tree("classification") %>% set_engine("xgboost", objective = logregobj),
    Class ~ .,
    bootstraps(two_class_dat, 5)
  )

collect_metrics(res)
#> # A tibble: 2 × 6
#>   .metric  .estimator  mean     n std_err .config             
#>   <chr>    <chr>      <dbl> <int>   <dbl> <chr>               
#> 1 accuracy binary     0.805     5 0.00676 Preprocessor1_Model1
#> 2 roc_auc  binary     0.865     5 0.00684 Preprocessor1_Model1
```

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by simonpcouch** [comment]
Does this do the trick for you, @SHo-JANG? You can install and test by running `pak::pak("tidymodels/parsnip#875")`, restarting R, and running your reprex.

**Comment by SHo-JANG** [comment]
It works surprisingly well. Thank you so much!😂

**Comment by simonpcouch** [comment]
Glad this is helpful for you! `xgb_predict()` is intended as a light wrapper around xgboost's predict method, so I think the scope of usage for this function will stay the same for now.

**Review by hfrick — APPROVED** [review]
nice!

**Pull request merged**
