### PR TITLE
temporarily mark survival models as internal

### PR DESCRIPTION
**Pull request by topepo**
Until censored is fully operational

### CODE REVIEW

**Comment by hfrick** [comment]
We soft-deprecated `surv_reg()`, i.e. it now gives a warning and tells you to use `survival_reg()`, the help file including examples points to the new function, and the help file itself is now also internal. So I'd say we either undo all of that or we don't make `survival_reg()` internal.

Are we also adapting the news file?

**Comment by juliasilge** [comment]
I do think we should take this out of the NEWS file and put it back in after it goes to CRAN, for the next release.

**Comment by topepo** [comment]
I've update the news file in the RC branch. 

I think the message is ok. It's not removed, just not listed (easily) in the help.

**Comment by hfrick** [comment]
okay sure, it just means that in this branch neither `surv_reg()` nor `survival_reg()` are listed in the documentation index. if you think that's fine then I have no more comments on this one :+1:

**Review by hfrick — APPROVED** [review]

**Pull request merged**
