### PR TITLE
Adding null model

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
in reference to #122.

Still WIP. Most of the skeleton is there but the `predict()` outputs length of fitting data not `new_data`.

### CODE REVIEW

**Comment by topepo** [comment]
Please use `type = "numeric"` for regression and `null_model` for the user-facing function. 

@DavisVaughan will get a laugh out of this but please lint the R code. Opening brackets should be on the same line as the function definition/`if` etc.

```r
null_model.default <- function(x = NULL, y, ...) {

}
```

Can you also enable multivariate numeric regression?

**Comment by EmilHvitfeldt** [comment]
> Can you also enable multivariate numeric regression?

Consider it done!

``` r
library(parsnip)

iris_basic <- null_model(mode = "regression") %>% 
  set_engine("parsnip") %>%
  fit(cbind(Sepal.Width) ~ ., data = iris)
  
predict_numeric(iris_basic, iris[1:5,])
#> [1] 3.057333 3.057333 3.057333 3.057333 3.057333

iris_basic <- null_model(mode = "regression") %>% 
  set_engine("parsnip") %>%
  fit(cbind(Sepal.Width, Petal.Width) ~ ., data = iris)
  
predict_numeric(iris_basic, iris[1:5,])
#>   Sepal.Width Petal.Width
#> 1    3.057333    1.199333
#> 2    3.057333    1.199333
#> 3    3.057333    1.199333
#> 4    3.057333    1.199333
#> 5    3.057333    1.199333
```

<sup>Created on 2019-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

While we are at it, should we also add `quantile` and `classprob`? It doesn't make sense to add `conf_int` and `pred_int`.

**Comment by topepo** [comment]
`type = "classprob"` would be helpful. I don't think that we have quantiles implemented anywhere so I'd hold off on that.

**Comment by topepo** [comment]
Thanks!

**Pull request merged**
